version: "2"

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - ireturn
    - depguard
    - nlreturn
    - exhaustruct
    - revive
    - staticcheck
    - wrapcheck
    - gochecknoglobals
